// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240329103117_RenameVillaNumbersTable")]
    partial class RenameVillaNumbersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreeatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreeatedDate = new DateTime(2024, 3, 29, 14, 31, 16, 973, DateTimeKind.Local).AddTicks(4013),
                            Details = "Villa Details",
                            ImageURL = "https://i.pinimg.com/736x/c9/63/7a/c9637a6a3716d65de5b91c38fbbd3f89.jpg",
                            Name = "Rayal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Private pool, beach access, BBQ area",
                            CreeatedDate = new DateTime(2024, 3, 29, 14, 31, 16, 973, DateTimeKind.Local).AddTicks(4026),
                            Details = "Luxury beachfront villa with stunning ocean views",
                            ImageURL = "https://www.beachhousenassau.com/wp-content/uploads/2018/10/Beach_House_Nassau_Ocean_View_Room1.jpg",
                            Name = "Ocean View Paradise",
                            Occupancy = 8,
                            Rate = 500.0,
                            Sqft = 1200,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Fireplace, hiking trails nearby, scenic views",
                            CreeatedDate = new DateTime(2024, 3, 29, 14, 31, 16, 973, DateTimeKind.Local).AddTicks(4027),
                            Details = "Cozy cabin nestled in the mountains, perfect for nature lovers",
                            ImageURL = "https://www.cabinsusa.com/uploads/images/units/828/828_1438040497_7935.jpg",
                            Name = "Mountain Retreat Cabin",
                            Occupancy = 4,
                            Rate = 150.0,
                            Sqft = 800,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Rooftop terrace, modern furnishings, city skyline views",
                            CreeatedDate = new DateTime(2024, 3, 29, 14, 31, 16, 973, DateTimeKind.Local).AddTicks(4028),
                            Details = "Chic loft apartment in the heart of the city",
                            ImageURL = "https://www.apartments.com/images/default-source/default-album/hero-photos/primary-hero-images/apartment-exterior-02-003.jpg?sfvrsn=f7bbd086_0",
                            Name = "Urban Loft",
                            Occupancy = 2,
                            Rate = 300.0,
                            Sqft = 700,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Wrap-around porch, garden, farm-to-table dining",
                            CreeatedDate = new DateTime(2024, 3, 29, 14, 31, 16, 973, DateTimeKind.Local).AddTicks(4030),
                            Details = "Quaint farmhouse surrounded by rolling hills and fields",
                            ImageURL = "https://media.istockphoto.com/photos/old-rustic-farmhouse-picture-id157708876?k=20&m=157708876&s=612x612&w=0&h=iW5YlBeuE0rM40voaLtwQh-QBebZZD3igDn7AATi6Wg=",
                            Name = "Rustic Farmhouse",
                            Occupancy = 6,
                            Rate = 250.0,
                            Sqft = 1000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VillaNo");

                    b.ToTable("VillaNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
